### ISSUE TITLE
カスタムドメインを適用する

### ISSUE THREAD

**Issue by necoffee-web** [neco3coffee/neco3coffee-site#10]
### 作業内容

- ドメインの取得
- [vercelのドキュメント](https://vercel.com/docs/projects/domains/add-a-domain)の確認
- カスタムドメインの適用

**Comment by neco3coffee** [comment]
以下のドキュメントや記事を参考に正常にDNSレコードの設定が完了し、無事に neco3coffee.meドメインでサイトにアクセスできたので close。

https://vercel.com/docs/projects/domains/deploying-and-redirecting#redirecting-www-domains

https://zuma-lab.com/posts/vercel-onamae-domain-settings

**Comment by necoffee-web** [comment]
以下のドキュメントや記事を参考に正常にDNSレコードの設定が完了し、無事に neco3coffee.meドメインでサイトにアクセスできたので close。

https://vercel.com/docs/projects/domains/deploying-and-redirecting#redirecting-www-domains

https://zuma-lab.com/posts/vercel-onamae-domain-settings
